version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 

  test:
    build: .
    depends_on:
      - flask-app
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=testing
    command: pytest tests
